### ISSUE TITLE
Submodule init doens't work for secret tasks

### ISSUE THREAD

**Issue by jorshi** [neuralaudio/hear-preprocess#95]
The command listed in the readme doesn't correctly add the secret task submodule.  I had to run this to get it to work properly: `git submodule add git@github.com:neuralaudio/hear2021-secret-tasks hearpreprocess/secrettasks`

https://stackoverflow.com/questions/3336995/git-will-not-init-sync-update-new-submodules

**Comment by turian** [comment]
@jorshi can you submit a PR?

**Comment by jorshi** [comment]
@turian see #96 -- this PR adds the submodule correctly so the README instructions work as intended now
